# Generated by Django 3.2 on 2024-02-20 22:21

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_confirmation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[(users.models.Roles['USER'], 'user'), (users.models.Roles['MODERATOR'], 'moderator'), (users.models.Roles['ADMIN'], 'admin')], default=users.models.Roles['USER'], max_length=10, verbose_name='Role'),
        ),
    ]
