# Generated by Django 3.2 on 2024-03-01 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role'),
        ('users', '0005_auto_20240222_0137'),
    ]

    operations = [
    ]
