# Generated by Django 3.2 on 2024-02-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.RemoveField(
            model_name='title',
            name='genres',
        ),
        migrations.AddField(
            model_name='title',
            name='genres',
            field=models.ManyToManyField(to='reviews.Genre'),
        ),
    ]
