# Generated by Django 3.2 on 2024-02-21 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_review_onli_one_rewiew'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='onli_one_rewiew',
        ),
    ]
