# Generated by Django 3.2 on 2024-02-21 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_remove_review_onli_one_rewiew'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='onli_one_rewiew'),
        ),
    ]
