# Generated by Django 3.2 on 2024-03-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_auto_20240225_1522'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='onli_one_review',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Заголовок'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_reviews'),
        ),
    ]
